language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - redis-server
before_install:
  #mysql
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - sudo mysql_upgrade --force
  - sudo service mysql restart
  #version add prepare
  - mvn install:install-file -DgroupId=cn.skill6.plugin -DartifactId=vautoadd-maven-plugin -Dversion=1.0.0 -Dpackaging=jar -Dfile=plugins/vautoadd-maven-plugin-1.0.0.jar
  #global setting
  - git config --global user.name "Travis Bot"
  - git config --global user.email "husen@hemingsheng.cn"
  #push to remote
  - cd skill6-parent
  - mvn vautoadd:vadd
  - echo "hello" >> test.txt
  - git add .
  - git commit -m "Updated Version By One By Travis"
  - git push -u origin master
  #zookeeper
  - sudo wget https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
  - tar -zxf zookeeper-3.4.13.tar.gz
  - cp zookeeper-3.4.13/conf/zoo_sample.cfg zookeeper-3.4.13/conf/zoo.cfg
  - ./zookeeper-3.4.13/bin/zkServer.sh start
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - SKILL6_MYSQL_PASSWROD=
    - SKILL6_MYSQL_URL="jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8"
    - SKILL6_MYSQL_USERNAME=root
    - SKILL6_REDIS_HOST=localhost
    - SKILL6_REDIS_PASSWORD=
    - SKILL6_REDIS_PORT=6379
